name: carwhats_mobile
description: "CarWhats Group - النظام المحاسبي المتكامل"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.0
  flutter_inappwebview: ^6.1.5
  google_fonts: ^6.2.1
  provider: ^6.1.2
  url_launcher: ^6.2.5
  connectivity_plus: ^6.1.0
  intl: any
  fl_chart: ^0.69.0
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  file_picker: ^8.0.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
